name: Cache dependencies
inputs:
  cache-on:
    description: "Whether to cache dependencies"
    required: false
    default: "true"
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.cache.outputs.cache-hit }}
  cache-enabled:
    description: "Whether caching is enabled"
    value: ${{ steps.install.outputs.cache-on }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies disabled
      if: inputs.cache-on == 'true'
      run: echo "Caching is enabled"
      shell: bash
    - name: Cache dependencies enabled
      if: inputs.cache-on == 'false'
      run: echo "Caching is disabled"
      shell: bash
    - name: Cache dependencies
      if: inputs.cache-on == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cache-on == 'false'
      id: install
      run: |
        npm ci
        echo "cache-on='${{ inputs.cache-on}}'" >> $GITHUB_OUTPUT
      shell: bash
